"""Turn the captured `receipt verify` runs into the demo's data module.

The transcripts on /receipt are not transcribed by hand: this reads the capture
files capture.py wrote and emits src/app/receipt/verify-transcripts.ts with each
run's stream text verbatim, so the only way the page can drift from receipt's
real output is for someone to edit a generated file.
"""

from __future__ import annotations

import json
import pathlib
import sys

CAPTURES = pathlib.Path(sys.argv[1]).resolve()
TARGET = pathlib.Path(sys.argv[2]).resolve()

# capture stem -> (attack id, pin state)
PLACEMENT = {
    "01-pristine": ("pristine", "none"),
    "03-base-ref-without-expect-commit": ("pristine", "baseRef"),
    "02-pristine-base-ref": ("pristine", "pinned"),
    "07-rewrite": ("rewrite", "none"),
    "17-hand-edit-base-ref-unpinned": ("rewrite", "baseRef"),
    "08-rewrite-base-ref": ("rewrite", "pinned"),
    "09-reencode": ("reencode", "none"),
    "18-re-encode-base-ref-unpinned": ("reencode", "baseRef"),
    "10-reencode-base-ref": ("reencode", "pinned"),
    "11-swapkey": ("swapkey", "none"),
    "19-swapped-key-base-ref-unpinned": ("swapkey", "baseRef"),
    "12-swapkey-base-ref": ("swapkey", "pinned"),
    "13-rewitness": ("rewitness", "none"),
    "20-regenerated-base-ref-unpinned": ("rewitness", "baseRef"),
    "14-rewitness-base-ref": ("rewitness", "pinned"),
    "15-dropgate": ("dropgate", "none"),
    "21-undeclared-gate-base-ref-unpinned": ("dropgate", "baseRef"),
    "16-dropgate-base-ref": ("dropgate", "pinned"),
}
ATTACKS = ["pristine", "rewrite", "reencode", "swapkey", "rewitness", "dropgate"]
PINS = ["none", "baseRef", "pinned"]


def parse(stem: str) -> dict[str, object]:
    text = (CAPTURES / f"{stem}.txt").read_text(encoding="utf-8")
    head, _, rest = text.partition("\n--- exit: ")
    command = head[len("$ ") :]
    code, _, streams = rest.partition("\n--- stdout ---\n")
    out, _, err = streams.partition("--- stderr ---\n")
    if out and err:
        raise SystemExit(f"{stem}: wrote to both streams; the demo assumes one")
    if not out and not err:
        raise SystemExit(f"{stem}: wrote nothing")
    # `python -m receipt.cli verify` and the installed `receipt verify` console
    # script are the same entry point; reproduce.py re-runs every scenario
    # through the console script and requires byte-identical output.
    command = command.replace("python -m receipt.cli ", "receipt ")
    return {
        "command": command,
        "exit": int(code),
        "stream": "stdout" if out else "stderr",
        "text": (out or err).rstrip("\n"),
    }


def literal(value: object) -> str:
    return json.dumps(value, ensure_ascii=False)


def template(text: str) -> str:
    """A TypeScript template literal holding `text` byte-for-byte.

    Emitting the transcripts as template literals rather than escaped strings
    is what makes a review of this file possible: the diff shows receipt's own
    lines, which a reader can hold against the capture files directly.
    """

    for forbidden in ("`", "\\", "${"):
        if forbidden in text:
            raise SystemExit(
                f"transcript contains {forbidden!r}, which a template literal "
                "cannot hold verbatim; emit it as an escaped string instead"
            )
    return f"`{text}`"


records: dict[str, dict[str, dict[str, object]]] = {a: {} for a in ATTACKS}
for stem, (attack, pin) in PLACEMENT.items():
    records[attack][pin] = parse(stem)

facts = json.loads((CAPTURES / "facts.json").read_text(encoding="utf-8"))

body = [
    # Every version this prose states is the captured one: a regeneration
    # against the next release must not emit a header that contradicts the
    # RECEIPT_VERSION below it, in a file whose second line forbids hand-edits.
    "// Generated by scripts/receipt-verify-demo/generate.py from receipt "
    f"{facts['receipt']}'s own output.",
    "// Do not hand-edit: see the module docstring below for how to regenerate.",
    "",
    "/**",
    " * Every `receipt verify` run the demo on /receipt shows, verbatim.",
    " *",
    f" * Captured from receipt {facts['receipt']} (PyPI) driven over the package's own signed",
    " * corpus fixture — `tests/corpus_fixture.py` at tag "
    f"v{facts['receipt']}, which stands up a",
    " * real hash-linked manifest chain, a real Ed25519 producer signature, and two",
    " * real RFC 3161 timestamp authorities in a fresh git repository. Four of the",
    " * scenarios mutate a private clone of that corpus, pristine is that clone",
    " * unmodified, and the undeclared-gate corpus is published separately under the",
    " * same producer key and the same two authorities — which is why its base ref",
    " * differs from every other run's. The spec module holding the trust anchors is",
    " * kept outside every tree under test, which is where receipt says anchors",
    " * belong.",
    " *",
    " * Nothing here is written by hand. `text` is the exact stream the command",
    " * wrote — stdout when the verdict passes, stderr when it refuses — with the",
    " * trailing newline stripped. The digests, commit OIDs and witness times are",
    " * one real run's, not illustrations of one.",
    " *",
    " * To regenerate after a receipt release, follow",
    " * scripts/receipt-verify-demo/README.md: capture.py drives the new version,",
    " * reproduce.py re-proves every capture through the installed console script,",
    " * and generate.py rewrites this file.",
    " */",
    "",
    f"export const RECEIPT_VERSION = {literal(facts['receipt'])};",
    "",
    "/** The corpus the transcripts are of, and the auditor's pins over it. */",
    "export const CORPUS = {",
    f"  fixture: {literal(facts['fixture'])},",
    f"  genesis: {literal(facts['genesis_commit'])},",
    f"  published: {literal(facts['published_commit'])},",
    f"  publishedTree: {literal(facts['published_tree'])},",
    f"  specSha256: {literal(facts['spec_sha256'])},",
    f"  producerSpki: {literal(facts['producer_spki'])},",
    "} as const;",
    "",
    "export type AttackId =",
    *[f'  | "{a}"' for a in ATTACKS[:-1]],
    f'  | "{ATTACKS[-1]}";',
    "",
    "/** How much the auditor pinned on the command line before running it. */",
    'export type Pin = "none" | "baseRef" | "pinned";',
    "",
    "export type Transcript = {",
    "  /** The invocation, as the capture recorded it. */",
    "  command: string;",
    "  exitCode: number;",
    '  /** receipt writes a passing verdict to stdout and a refusal to stderr. */',
    '  stream: "stdout" | "stderr";',
    "  /** The stream's exact text. */",
    "  text: string;",
    "};",
    "",
    "export const TRANSCRIPTS: Record<AttackId, Record<Pin, Transcript>> = {",
]

for attack in ATTACKS:
    body.append(f"  {attack}: {{")
    for pin in PINS:
        record = records[attack][pin]
        body.append(f"    {pin}: {{")
        body.append(f"      command: {literal(record['command'])},")
        body.append(f"      exitCode: {record['exit']},")
        body.append(f"      stream: {literal(record['stream'])},")
        body.append(f"      text: {template(str(record['text']))},")
        body.append("    },")
    body.append("  },")
body.append("};")
body.append("")
body.append("/** What each attack's clone actually is, for the tree pane beside it. */")
body.append(
    "export const CLONES: Record<AttackId, "
    "{ commit: string; tree: string; manifests: readonly string[] }> = {"
)
for attack in ATTACKS:
    clone = facts["clones"][attack]
    body.append(f"  {attack}: {{")
    body.append(f"    commit: {literal(clone['commit'])},")
    body.append(f"    tree: {literal(clone['tree'])},")
    body.append(f"    manifests: {literal(clone['manifests'])},")
    body.append("  },")
body.append("};")
body.append("")

TARGET.write_text("\n".join(body), encoding="utf-8")
print(f"wrote {TARGET} ({len(body)} lines)")
