// Generated by scripts/receipt-verify-demo/generate.py from receipt 0.6.1's own output.
// Do not hand-edit: see the module docstring below for how to regenerate.

/**
 * Every `receipt verify` run the demo on /receipt shows, verbatim.
 *
 * Captured from receipt 0.6.1 (PyPI) driven over the package's own signed
 * corpus fixture — `tests/corpus_fixture.py` at tag v0.6.1, which stands up a
 * real hash-linked manifest chain, a real Ed25519 producer signature, and two
 * real RFC 3161 timestamp authorities in a fresh git repository. Four of the
 * scenarios mutate a private clone of that corpus, pristine is that clone
 * unmodified, and the undeclared-gate corpus is published separately under the
 * same producer key and the same two authorities — which is why its base ref
 * differs from every other run's. The spec module holding the trust anchors is
 * kept outside every tree under test, which is where receipt says anchors
 * belong.
 *
 * Nothing here is written by hand. `text` is the exact stream the command
 * wrote — stdout when the verdict passes, stderr when it refuses — with the
 * trailing newline stripped. The digests, commit OIDs and witness times are
 * one real run's, not illustrations of one.
 *
 * To regenerate after a receipt release, follow
 * scripts/receipt-verify-demo/README.md: capture.py drives the new version,
 * reproduce.py re-proves every capture through the installed console script,
 * and generate.py rewrites this file.
 */

export const RECEIPT_VERSION = "0.6.1";

/** The corpus the transcripts are of, and the auditor's pins over it. */
export const CORPUS = {
  fixture: "TheAxiomFoundation/receipt @ v0.6.1 tests/corpus_fixture.py",
  genesis: "7638589283c22fd727e5b0a8888fc07f312da8bc",
  published: "324eaab3964f1a8d3aa20ea87d3b4037acade8a9",
  publishedTree: "0b3400c8e44e864677d731088e0b8dc1bd65a484",
  specSha256: "48722e00b717b1b6c3a384b836947df63a458c560e7601daff7eefaee8f3a2b2",
  producerSpki: "8595923745cbbef67548dc1526252097f1ed0261283e72b0e31e803046846f97",
} as const;

export type AttackId =
  | "pristine"
  | "rewrite"
  | "reencode"
  | "swapkey"
  | "rewitness"
  | "dropgate";

/** How much the auditor pinned on the command line before running it. */
export type Pin = "none" | "baseRef" | "pinned";

export type Transcript = {
  /** The invocation, as the capture recorded it. */
  command: string;
  exitCode: number;
  /** receipt writes a passing verdict to stdout and a refusal to stderr. */
  stream: "stdout" | "stderr";
  /** The stream's exact text. */
  text: string;
};

export const TRANSCRIPTS: Record<AttackId, Record<Pin, Transcript>> = {
  pristine: {
    none: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/pristine/corpus --commit HEAD",
      exitCode: 0,
      stream: "stdout",
      text: `receipt 0.6.1 — receipt test corpus
  root  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/pristine/corpus
  commit 324eaab3964f1a8d3aa20ea87d3b4037acade8a9 (tree 0b3400c8e44e864677d731088e0b8dc1bd65a484)
  names portable
  objects not requested
  spec  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py
        sha256 48722e00b717b1b6c3a384b836947df63a458c560e7601daff7eefaee8f3a2b2

ESTABLISHED OFFLINE, FROM THIS CLONE ALONE
  [ok  ] custody
         2 release(s), HEAD 0001-8e2318a7a183ff21.json; head 8e2318a7a183ff215d4cc68bdcb189992ce13eaa4f799128a6f1d013938e6c03; producer SPKI 8595923745cbbef6…; anchor set a3021009fb99d91430045c960871842f2b33aa4b99c9c786b38218f30551192a; witnesses alpha 2026-09-10T12:28:49Z · beta 2026-09-10T12:28:49Z
  [ok  ] binding
         3 content file(s) and 1 attested file(s) match the witnessed journal exactly, closed-world
  [ok  ] declaration
         3 gate declaration(s) well formed and complete against the loaded spec (1 public, 1 restricted, 1 ci-attested); none re-run here

DECLARED IN THE WITNESSED JOURNAL — NOT RE-RUN BY THIS COMMAND
  public: you can re-run these yourself from public inputs
    - rulespec/compile
  restricted: reproducible only with restricted pinned inputs this command cannot obtain
    - oracle/licensed-parity
  ci-attested: not reproducible; only the CI run's identity vouches
    - ci/repository-checks

VERDICT: PASS — custody and corpus binding
  This proves the published rule files are exactly the bytes the loaded
  spec's producer key signed,
  and the 2 RFC 3161 authorities configured by that spec (alpha, beta)
  witnessed that each recorded prefix existed no later than those times.
  Custody is under the anchor set a3021009fb99d91430045c960871842f2b33aa4b99c9c786b38218f30551192a the verified tree carries.
  It does NOT prove the history was never rewritten — a producer holding
  the signing key can regenerate and re-witness a whole chain, and this
  first-contact check would still pass; supply --base-ref against a head
  you recorded earlier to bind against that. It does
  NOT prove that any declared gate passed, it does NOT prove the encodings
  are a correct reading of the law, it does NOT prove this clone holds the
  producer's newest release, and it does NOT prove this is the only history
  the producer maintains — a stale or equivocated but honestly witnessed
  clone may pass, and this verdict does NOT prove that files in any checkout
  equal the verified tree.
  It does NOT establish that the spec's code was trusted.
  It does NOT establish that the anchor set is one the auditor trusts.
  Check freshness and uniqueness by comparing head
  digests out of band.`,
    },
    baseRef: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/pristine/corpus --commit HEAD --base-ref 7638589283c22fd727e5b0a8888fc07f312da8bc",
      exitCode: 2,
      stream: "stderr",
      text: `receipt verify: --base-ref requires --expect-commit
receipt verify: FAIL`,
    },
    pinned: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/pristine/corpus --commit HEAD --expect-commit 324eaab3964f1a8d3aa20ea87d3b4037acade8a9 --base-ref 7638589283c22fd727e5b0a8888fc07f312da8bc",
      exitCode: 0,
      stream: "stdout",
      text: `receipt 0.6.1 — receipt test corpus
  root  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/pristine/corpus
  commit 324eaab3964f1a8d3aa20ea87d3b4037acade8a9 (tree 0b3400c8e44e864677d731088e0b8dc1bd65a484)
  base 7638589283c22fd727e5b0a8888fc07f312da8bc (tree 54ad835fffec7bc72710bd041f7246466e2db320)
  names portable
  objects not requested
  spec  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py
        sha256 48722e00b717b1b6c3a384b836947df63a458c560e7601daff7eefaee8f3a2b2

ESTABLISHED OFFLINE, FROM THIS CLONE ALONE
  [ok  ] history
         every release object present at 7638589283c22fd727e5b0a8888fc07f312da8bc (7638589283c22fd727e5b0a8888fc07f312da8bc) is byte- and mode-identical in tree 0b3400c8e44e
  [ok  ] custody
         2 release(s), HEAD 0001-8e2318a7a183ff21.json; head 8e2318a7a183ff215d4cc68bdcb189992ce13eaa4f799128a6f1d013938e6c03; producer SPKI 8595923745cbbef6…; anchor set a3021009fb99d91430045c960871842f2b33aa4b99c9c786b38218f30551192a; witnesses alpha 2026-09-10T12:28:49Z · beta 2026-09-10T12:28:49Z
  [ok  ] binding
         3 content file(s) and 1 attested file(s) match the witnessed journal exactly, closed-world
  [ok  ] declaration
         3 gate declaration(s) well formed and complete against the loaded spec (1 public, 1 restricted, 1 ci-attested); none re-run here

DECLARED IN THE WITNESSED JOURNAL — NOT RE-RUN BY THIS COMMAND
  public: you can re-run these yourself from public inputs
    - rulespec/compile
  restricted: reproducible only with restricted pinned inputs this command cannot obtain
    - oracle/licensed-parity
  ci-attested: not reproducible; only the CI run's identity vouches
    - ci/repository-checks

VERDICT: PASS — custody and corpus binding
  This proves the published rule files are exactly the bytes the loaded
  spec's producer key signed,
  and the 2 RFC 3161 authorities configured by that spec (alpha, beta)
  witnessed that each recorded prefix existed no later than those times,
  and every release object present at the supplied base reference is
  byte- and mode-identical in this tree.
  Custody is under the anchor set a3021009fb99d91430045c960871842f2b33aa4b99c9c786b38218f30551192a the verified tree carries.
  It does
  NOT prove that any declared gate passed, it does NOT prove the encodings
  are a correct reading of the law, it does NOT prove this clone holds the
  producer's newest release, and it does NOT prove this is the only history
  the producer maintains — a stale or equivocated but honestly witnessed
  clone may pass, and this verdict does NOT prove that files in any checkout
  equal the verified tree.
  It does NOT establish that the spec's code was trusted.
  It does NOT establish that the anchor set is one the auditor trusts.
  Check freshness and uniqueness by comparing head
  digests out of band.`,
    },
  },
  rewrite: {
    none: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/hand-edit/corpus --commit HEAD",
      exitCode: 1,
      stream: "stderr",
      text: `receipt 0.6.1 — receipt test corpus
  root  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/hand-edit/corpus
  commit 95981326fc8e4961c103a4c81f9ae216ee628bfb (tree 13bd8b50b2f4e0dd0390bfc13c636ba8279d2ea9)
  names portable
  objects not requested
  spec  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py
        sha256 48722e00b717b1b6c3a384b836947df63a458c560e7601daff7eefaee8f3a2b2

PASSES
  [ok  ] custody
         2 release(s), HEAD 0001-8e2318a7a183ff21.json; head 8e2318a7a183ff215d4cc68bdcb189992ce13eaa4f799128a6f1d013938e6c03; producer SPKI 8595923745cbbef6…; anchor set a3021009fb99d91430045c960871842f2b33aa4b99c9c786b38218f30551192a; witnesses alpha 2026-09-10T12:28:49Z · beta 2026-09-10T12:28:49Z
  [FAIL] binding
         content file 'rules/tax/rate.yaml' does not match its witnessed digest: tree has c0f597cf00ba8050cdd6c8578e255c2bf364d1a00890b50d092bfd5df1f47348, journal binds e218ac6d2f126c76eb6e74203814e06e3fd528afc809576cede2e2b2546bdc49
  [FAIL] declaration
         not reached

FAILED: binding
  content file 'rules/tax/rate.yaml' does not match its witnessed digest: tree has c0f597cf00ba8050cdd6c8578e255c2bf364d1a00890b50d092bfd5df1f47348, journal binds e218ac6d2f126c76eb6e74203814e06e3fd528afc809576cede2e2b2546bdc49

VERDICT: FAIL — binding`,
    },
    baseRef: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/hand-edit/corpus --commit HEAD --base-ref 7638589283c22fd727e5b0a8888fc07f312da8bc",
      exitCode: 2,
      stream: "stderr",
      text: `receipt verify: --base-ref requires --expect-commit
receipt verify: FAIL`,
    },
    pinned: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/hand-edit/corpus --commit HEAD --expect-commit 95981326fc8e4961c103a4c81f9ae216ee628bfb --base-ref 7638589283c22fd727e5b0a8888fc07f312da8bc",
      exitCode: 1,
      stream: "stderr",
      text: `receipt 0.6.1 — receipt test corpus
  root  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/hand-edit/corpus
  commit 95981326fc8e4961c103a4c81f9ae216ee628bfb (tree 13bd8b50b2f4e0dd0390bfc13c636ba8279d2ea9)
  base 7638589283c22fd727e5b0a8888fc07f312da8bc (tree 54ad835fffec7bc72710bd041f7246466e2db320)
  names portable
  objects not requested
  spec  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py
        sha256 48722e00b717b1b6c3a384b836947df63a458c560e7601daff7eefaee8f3a2b2

PASSES
  [ok  ] history
         every release object present at 7638589283c22fd727e5b0a8888fc07f312da8bc (7638589283c22fd727e5b0a8888fc07f312da8bc) is byte- and mode-identical in tree 13bd8b50b2f4
  [ok  ] custody
         2 release(s), HEAD 0001-8e2318a7a183ff21.json; head 8e2318a7a183ff215d4cc68bdcb189992ce13eaa4f799128a6f1d013938e6c03; producer SPKI 8595923745cbbef6…; anchor set a3021009fb99d91430045c960871842f2b33aa4b99c9c786b38218f30551192a; witnesses alpha 2026-09-10T12:28:49Z · beta 2026-09-10T12:28:49Z
  [FAIL] binding
         content file 'rules/tax/rate.yaml' does not match its witnessed digest: tree has c0f597cf00ba8050cdd6c8578e255c2bf364d1a00890b50d092bfd5df1f47348, journal binds e218ac6d2f126c76eb6e74203814e06e3fd528afc809576cede2e2b2546bdc49
  [FAIL] declaration
         not reached

FAILED: binding
  content file 'rules/tax/rate.yaml' does not match its witnessed digest: tree has c0f597cf00ba8050cdd6c8578e255c2bf364d1a00890b50d092bfd5df1f47348, journal binds e218ac6d2f126c76eb6e74203814e06e3fd528afc809576cede2e2b2546bdc49

VERDICT: FAIL — binding`,
    },
  },
  reencode: {
    none: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/re-encode/corpus --commit HEAD",
      exitCode: 0,
      stream: "stdout",
      text: `receipt 0.6.1 — receipt test corpus
  root  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/re-encode/corpus
  commit 1eab501bf3a407fdcdf1b9ce02b502ce83ebe42c (tree 2c385fcedd021945d89c1ef34649aafc69add9e3)
  names portable
  objects not requested
  spec  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py
        sha256 48722e00b717b1b6c3a384b836947df63a458c560e7601daff7eefaee8f3a2b2

ESTABLISHED OFFLINE, FROM THIS CLONE ALONE
  [ok  ] custody
         3 release(s), HEAD 0002-ed0cfdc5b9c5d746.json; head ed0cfdc5b9c5d7466aa53057e0d4e8e25b1e4ac730924bf9dd3a991d1e9cb6f1; producer SPKI 8595923745cbbef6…; anchor set a3021009fb99d91430045c960871842f2b33aa4b99c9c786b38218f30551192a; witnesses alpha 2026-09-10T12:28:51Z · beta 2026-09-10T12:28:51Z
  [ok  ] binding
         3 content file(s) and 1 attested file(s) match the witnessed journal exactly, closed-world
  [ok  ] declaration
         3 gate declaration(s) well formed and complete against the loaded spec (1 public, 1 restricted, 1 ci-attested); none re-run here

DECLARED IN THE WITNESSED JOURNAL — NOT RE-RUN BY THIS COMMAND
  public: you can re-run these yourself from public inputs
    - rulespec/compile
  restricted: reproducible only with restricted pinned inputs this command cannot obtain
    - oracle/licensed-parity
  ci-attested: not reproducible; only the CI run's identity vouches
    - ci/repository-checks

VERDICT: PASS — custody and corpus binding
  This proves the published rule files are exactly the bytes the loaded
  spec's producer key signed,
  and the 2 RFC 3161 authorities configured by that spec (alpha, beta)
  witnessed that each recorded prefix existed no later than those times.
  Custody is under the anchor set a3021009fb99d91430045c960871842f2b33aa4b99c9c786b38218f30551192a the verified tree carries.
  It does NOT prove the history was never rewritten — a producer holding
  the signing key can regenerate and re-witness a whole chain, and this
  first-contact check would still pass; supply --base-ref against a head
  you recorded earlier to bind against that. It does
  NOT prove that any declared gate passed, it does NOT prove the encodings
  are a correct reading of the law, it does NOT prove this clone holds the
  producer's newest release, and it does NOT prove this is the only history
  the producer maintains — a stale or equivocated but honestly witnessed
  clone may pass, and this verdict does NOT prove that files in any checkout
  equal the verified tree.
  It does NOT establish that the spec's code was trusted.
  It does NOT establish that the anchor set is one the auditor trusts.
  Check freshness and uniqueness by comparing head
  digests out of band.`,
    },
    baseRef: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/re-encode/corpus --commit HEAD --base-ref 7638589283c22fd727e5b0a8888fc07f312da8bc",
      exitCode: 2,
      stream: "stderr",
      text: `receipt verify: --base-ref requires --expect-commit
receipt verify: FAIL`,
    },
    pinned: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/re-encode/corpus --commit HEAD --expect-commit 1eab501bf3a407fdcdf1b9ce02b502ce83ebe42c --base-ref 7638589283c22fd727e5b0a8888fc07f312da8bc",
      exitCode: 0,
      stream: "stdout",
      text: `receipt 0.6.1 — receipt test corpus
  root  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/re-encode/corpus
  commit 1eab501bf3a407fdcdf1b9ce02b502ce83ebe42c (tree 2c385fcedd021945d89c1ef34649aafc69add9e3)
  base 7638589283c22fd727e5b0a8888fc07f312da8bc (tree 54ad835fffec7bc72710bd041f7246466e2db320)
  names portable
  objects not requested
  spec  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py
        sha256 48722e00b717b1b6c3a384b836947df63a458c560e7601daff7eefaee8f3a2b2

ESTABLISHED OFFLINE, FROM THIS CLONE ALONE
  [ok  ] history
         every release object present at 7638589283c22fd727e5b0a8888fc07f312da8bc (7638589283c22fd727e5b0a8888fc07f312da8bc) is byte- and mode-identical in tree 2c385fcedd02
  [ok  ] custody
         3 release(s), HEAD 0002-ed0cfdc5b9c5d746.json; head ed0cfdc5b9c5d7466aa53057e0d4e8e25b1e4ac730924bf9dd3a991d1e9cb6f1; producer SPKI 8595923745cbbef6…; anchor set a3021009fb99d91430045c960871842f2b33aa4b99c9c786b38218f30551192a; witnesses alpha 2026-09-10T12:28:51Z · beta 2026-09-10T12:28:51Z
  [ok  ] binding
         3 content file(s) and 1 attested file(s) match the witnessed journal exactly, closed-world
  [ok  ] declaration
         3 gate declaration(s) well formed and complete against the loaded spec (1 public, 1 restricted, 1 ci-attested); none re-run here

DECLARED IN THE WITNESSED JOURNAL — NOT RE-RUN BY THIS COMMAND
  public: you can re-run these yourself from public inputs
    - rulespec/compile
  restricted: reproducible only with restricted pinned inputs this command cannot obtain
    - oracle/licensed-parity
  ci-attested: not reproducible; only the CI run's identity vouches
    - ci/repository-checks

VERDICT: PASS — custody and corpus binding
  This proves the published rule files are exactly the bytes the loaded
  spec's producer key signed,
  and the 2 RFC 3161 authorities configured by that spec (alpha, beta)
  witnessed that each recorded prefix existed no later than those times,
  and every release object present at the supplied base reference is
  byte- and mode-identical in this tree.
  Custody is under the anchor set a3021009fb99d91430045c960871842f2b33aa4b99c9c786b38218f30551192a the verified tree carries.
  It does
  NOT prove that any declared gate passed, it does NOT prove the encodings
  are a correct reading of the law, it does NOT prove this clone holds the
  producer's newest release, and it does NOT prove this is the only history
  the producer maintains — a stale or equivocated but honestly witnessed
  clone may pass, and this verdict does NOT prove that files in any checkout
  equal the verified tree.
  It does NOT establish that the spec's code was trusted.
  It does NOT establish that the anchor set is one the auditor trusts.
  Check freshness and uniqueness by comparing head
  digests out of band.`,
    },
  },
  swapkey: {
    none: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/swapped-key/corpus --commit HEAD",
      exitCode: 1,
      stream: "stderr",
      text: `receipt 0.6.1 — receipt test corpus
  root  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/swapped-key/corpus
  commit 468d6be63dcbf2e559857942a1150fa46243b161 (tree dba57b71510f329f1e993952c69fc40b6337bf79)
  names portable
  objects not requested
  spec  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py
        sha256 48722e00b717b1b6c3a384b836947df63a458c560e7601daff7eefaee8f3a2b2

PASSES
  [FAIL] custody
         producer public-key SPKI is not code-pinned: 527be85155f215b983c1ee8e88d2c121ffea40a25f0ee77fa91a42d3e9672afb
  [FAIL] binding
         not reached

FAILED: custody
  producer public-key SPKI is not code-pinned: 527be85155f215b983c1ee8e88d2c121ffea40a25f0ee77fa91a42d3e9672afb

VERDICT: FAIL — custody`,
    },
    baseRef: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/swapped-key/corpus --commit HEAD --base-ref 7638589283c22fd727e5b0a8888fc07f312da8bc",
      exitCode: 2,
      stream: "stderr",
      text: `receipt verify: --base-ref requires --expect-commit
receipt verify: FAIL`,
    },
    pinned: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/swapped-key/corpus --commit HEAD --expect-commit 468d6be63dcbf2e559857942a1150fa46243b161 --base-ref 7638589283c22fd727e5b0a8888fc07f312da8bc",
      exitCode: 1,
      stream: "stderr",
      text: `receipt 0.6.1 — receipt test corpus
  root  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/swapped-key/corpus
  commit 468d6be63dcbf2e559857942a1150fa46243b161 (tree dba57b71510f329f1e993952c69fc40b6337bf79)
  base 7638589283c22fd727e5b0a8888fc07f312da8bc (tree 54ad835fffec7bc72710bd041f7246466e2db320)
  names portable
  objects not requested
  spec  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py
        sha256 48722e00b717b1b6c3a384b836947df63a458c560e7601daff7eefaee8f3a2b2

PASSES
  [FAIL] history
         release history is not immutable: existing release file bytes changed relative to 7638589283c22fd727e5b0a8888fc07f312da8bc: releases/anchors/producer-ed25519.pub
  [FAIL] custody
         not reached

FAILED: history
  release history is not immutable: existing release file bytes changed relative to 7638589283c22fd727e5b0a8888fc07f312da8bc: releases/anchors/producer-ed25519.pub

VERDICT: FAIL — history`,
    },
  },
  rewitness: {
    none: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/regenerated/corpus --commit HEAD",
      exitCode: 0,
      stream: "stdout",
      text: `receipt 0.6.1 — receipt test corpus
  root  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/regenerated/corpus
  commit f7e1129fc6d66e0f5c26b02927855234dbf44e2a (tree 7718046defbe185c57017f4c9a3879d50fdeb687)
  names portable
  objects not requested
  spec  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py
        sha256 48722e00b717b1b6c3a384b836947df63a458c560e7601daff7eefaee8f3a2b2

ESTABLISHED OFFLINE, FROM THIS CLONE ALONE
  [ok  ] custody
         2 release(s), HEAD 0001-8b01c373a1fc6d2d.json; head 8b01c373a1fc6d2d9acc771644e522781a71d0b04a04212140b3cebab75e9b8e; producer SPKI 8595923745cbbef6…; anchor set a3021009fb99d91430045c960871842f2b33aa4b99c9c786b38218f30551192a; witnesses alpha 2026-09-10T12:28:52Z · beta 2026-09-10T12:28:52Z
  [ok  ] binding
         3 content file(s) and 1 attested file(s) match the witnessed journal exactly, closed-world
  [ok  ] declaration
         3 gate declaration(s) well formed and complete against the loaded spec (1 public, 1 restricted, 1 ci-attested); none re-run here

DECLARED IN THE WITNESSED JOURNAL — NOT RE-RUN BY THIS COMMAND
  public: you can re-run these yourself from public inputs
    - rulespec/compile
  restricted: reproducible only with restricted pinned inputs this command cannot obtain
    - oracle/licensed-parity
  ci-attested: not reproducible; only the CI run's identity vouches
    - ci/repository-checks

VERDICT: PASS — custody and corpus binding
  This proves the published rule files are exactly the bytes the loaded
  spec's producer key signed,
  and the 2 RFC 3161 authorities configured by that spec (alpha, beta)
  witnessed that each recorded prefix existed no later than those times.
  Custody is under the anchor set a3021009fb99d91430045c960871842f2b33aa4b99c9c786b38218f30551192a the verified tree carries.
  It does NOT prove the history was never rewritten — a producer holding
  the signing key can regenerate and re-witness a whole chain, and this
  first-contact check would still pass; supply --base-ref against a head
  you recorded earlier to bind against that. It does
  NOT prove that any declared gate passed, it does NOT prove the encodings
  are a correct reading of the law, it does NOT prove this clone holds the
  producer's newest release, and it does NOT prove this is the only history
  the producer maintains — a stale or equivocated but honestly witnessed
  clone may pass, and this verdict does NOT prove that files in any checkout
  equal the verified tree.
  It does NOT establish that the spec's code was trusted.
  It does NOT establish that the anchor set is one the auditor trusts.
  Check freshness and uniqueness by comparing head
  digests out of band.`,
    },
    baseRef: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/regenerated/corpus --commit HEAD --base-ref 7638589283c22fd727e5b0a8888fc07f312da8bc",
      exitCode: 2,
      stream: "stderr",
      text: `receipt verify: --base-ref requires --expect-commit
receipt verify: FAIL`,
    },
    pinned: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/regenerated/corpus --commit HEAD --expect-commit f7e1129fc6d66e0f5c26b02927855234dbf44e2a --base-ref 7638589283c22fd727e5b0a8888fc07f312da8bc",
      exitCode: 1,
      stream: "stderr",
      text: `receipt 0.6.1 — receipt test corpus
  root  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/regenerated/corpus
  commit f7e1129fc6d66e0f5c26b02927855234dbf44e2a (tree 7718046defbe185c57017f4c9a3879d50fdeb687)
  base 7638589283c22fd727e5b0a8888fc07f312da8bc (tree 54ad835fffec7bc72710bd041f7246466e2db320)
  names portable
  objects not requested
  spec  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py
        sha256 48722e00b717b1b6c3a384b836947df63a458c560e7601daff7eefaee8f3a2b2

PASSES
  [FAIL] history
         release history is not immutable: existing release file was deleted relative to 7638589283c22fd727e5b0a8888fc07f312da8bc: releases/manifests/0000-a9f4956530a6b22c.alpha.tsr
  [FAIL] custody
         not reached

FAILED: history
  release history is not immutable: existing release file was deleted relative to 7638589283c22fd727e5b0a8888fc07f312da8bc: releases/manifests/0000-a9f4956530a6b22c.alpha.tsr

VERDICT: FAIL — history`,
    },
  },
  dropgate: {
    none: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/undeclared-gate/corpus --commit HEAD",
      exitCode: 1,
      stream: "stderr",
      text: `receipt 0.6.1 — receipt test corpus
  root  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/undeclared-gate/corpus
  commit f4e6fbdb672b8a7a540d3aef2964ce4770195a89 (tree 1e684f8f0275bef9242615d9c496ccf900220270)
  names portable
  objects not requested
  spec  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py
        sha256 48722e00b717b1b6c3a384b836947df63a458c560e7601daff7eefaee8f3a2b2

PASSES
  [ok  ] custody
         2 release(s), HEAD 0001-3c103c569788f63e.json; head 3c103c569788f63ee66f713a8faa1aae6d0d7ad080e58bcb9c21e80613a746d9; producer SPKI 8595923745cbbef6…; anchor set a3021009fb99d91430045c960871842f2b33aa4b99c9c786b38218f30551192a; witnesses alpha 2026-09-10T12:28:53Z · beta 2026-09-10T12:28:53Z
  [ok  ] binding
         3 content file(s) and 1 attested file(s) match the witnessed journal exactly, closed-world
  [FAIL] declaration
         the witnessed journal does not declare a gate the pinned spec requires: 'rulespec/compile'

DECLARED IN THE WITNESSED JOURNAL — NOT RE-RUN BY THIS COMMAND
  restricted: reproducible only with restricted pinned inputs this command cannot obtain
    - oracle/licensed-parity
  ci-attested: not reproducible; only the CI run's identity vouches
    - ci/repository-checks

FAILED: declaration
  the witnessed journal does not declare a gate the pinned spec requires: 'rulespec/compile'

VERDICT: FAIL — declaration`,
    },
    baseRef: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/undeclared-gate/corpus --commit HEAD --base-ref 34e0a8985869153511cdcc2e5c2b43a8d95a9ed9",
      exitCode: 2,
      stream: "stderr",
      text: `receipt verify: --base-ref requires --expect-commit
receipt verify: FAIL`,
    },
    pinned: {
      command: "receipt verify --spec /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py --root /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/undeclared-gate/corpus --commit HEAD --expect-commit f4e6fbdb672b8a7a540d3aef2964ce4770195a89 --base-ref 34e0a8985869153511cdcc2e5c2b43a8d95a9ed9",
      exitCode: 1,
      stream: "stderr",
      text: `receipt 0.6.1 — receipt test corpus
  root  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/undeclared-gate/corpus
  commit f4e6fbdb672b8a7a540d3aef2964ce4770195a89 (tree 1e684f8f0275bef9242615d9c496ccf900220270)
  base 34e0a8985869153511cdcc2e5c2b43a8d95a9ed9 (tree bf3d79449cda1f5a23468c8bddf12a6704ab8ebb)
  names portable
  objects not requested
  spec  /private/tmp/claude-501/-Users-maxghenis/582ab8c8-c5ec-4f48-8f2c-8cafa7906359/scratchpad/receipt-demo-061/demo/auditor/spec.py
        sha256 48722e00b717b1b6c3a384b836947df63a458c560e7601daff7eefaee8f3a2b2

PASSES
  [ok  ] history
         every release object present at 34e0a8985869153511cdcc2e5c2b43a8d95a9ed9 (34e0a8985869153511cdcc2e5c2b43a8d95a9ed9) is byte- and mode-identical in tree 1e684f8f0275
  [ok  ] custody
         2 release(s), HEAD 0001-3c103c569788f63e.json; head 3c103c569788f63ee66f713a8faa1aae6d0d7ad080e58bcb9c21e80613a746d9; producer SPKI 8595923745cbbef6…; anchor set a3021009fb99d91430045c960871842f2b33aa4b99c9c786b38218f30551192a; witnesses alpha 2026-09-10T12:28:53Z · beta 2026-09-10T12:28:53Z
  [ok  ] binding
         3 content file(s) and 1 attested file(s) match the witnessed journal exactly, closed-world
  [FAIL] declaration
         the witnessed journal does not declare a gate the pinned spec requires: 'rulespec/compile'

DECLARED IN THE WITNESSED JOURNAL — NOT RE-RUN BY THIS COMMAND
  restricted: reproducible only with restricted pinned inputs this command cannot obtain
    - oracle/licensed-parity
  ci-attested: not reproducible; only the CI run's identity vouches
    - ci/repository-checks

FAILED: declaration
  the witnessed journal does not declare a gate the pinned spec requires: 'rulespec/compile'

VERDICT: FAIL — declaration`,
    },
  },
};

/** What each attack's clone actually is, for the tree pane beside it. */
export const CLONES: Record<AttackId, { commit: string; tree: string; manifests: readonly string[] }> = {
  pristine: {
    commit: "324eaab3964f1a8d3aa20ea87d3b4037acade8a9",
    tree: "0b3400c8e44e864677d731088e0b8dc1bd65a484",
    manifests: ["0000-a9f4956530a6b22c.json", "0001-8e2318a7a183ff21.json"],
  },
  rewrite: {
    commit: "95981326fc8e4961c103a4c81f9ae216ee628bfb",
    tree: "13bd8b50b2f4e0dd0390bfc13c636ba8279d2ea9",
    manifests: ["0000-a9f4956530a6b22c.json", "0001-8e2318a7a183ff21.json"],
  },
  reencode: {
    commit: "1eab501bf3a407fdcdf1b9ce02b502ce83ebe42c",
    tree: "2c385fcedd021945d89c1ef34649aafc69add9e3",
    manifests: ["0000-a9f4956530a6b22c.json", "0001-8e2318a7a183ff21.json", "0002-ed0cfdc5b9c5d746.json"],
  },
  swapkey: {
    commit: "468d6be63dcbf2e559857942a1150fa46243b161",
    tree: "dba57b71510f329f1e993952c69fc40b6337bf79",
    manifests: ["0000-a9f4956530a6b22c.json", "0001-8e2318a7a183ff21.json"],
  },
  rewitness: {
    commit: "f7e1129fc6d66e0f5c26b02927855234dbf44e2a",
    tree: "7718046defbe185c57017f4c9a3879d50fdeb687",
    manifests: ["0000-960a1566a3c51962.json", "0001-8b01c373a1fc6d2d.json"],
  },
  dropgate: {
    commit: "f4e6fbdb672b8a7a540d3aef2964ce4770195a89",
    tree: "1e684f8f0275bef9242615d9c496ccf900220270",
    manifests: ["0000-dafe44823ca82e48.json", "0001-3c103c569788f63e.json"],
  },
};
