// Generated by scripts/receipt-verify-demo/generate.py from receipt 0.6.0's own output.
// Do not hand-edit: see the module docstring below for how to regenerate.

/**
 * Every `receipt verify` run the demo on /receipt shows, verbatim.
 *
 * Captured from receipt 0.6.0 (PyPI) driven over the package's own signed
 * corpus fixture — `tests/corpus_fixture.py` at tag v0.6.0, which stands up a
 * real hash-linked manifest chain, a real Ed25519 producer signature, and two
 * real RFC 3161 timestamp authorities in a fresh git repository. Four of the
 * scenarios mutate a private clone of that corpus, pristine is that clone
 * unmodified, and the undeclared-gate corpus is published separately under the
 * same producer key and the same two authorities — which is why its base ref
 * differs from every other run's. The spec module holding the trust anchors is
 * kept outside every tree under test, which is where receipt says anchors
 * belong.
 *
 * Nothing here is written by hand. `text` is the exact stream the command
 * wrote — stdout when the verdict passes, stderr when it refuses — with the
 * trailing newline stripped. The digests, commit OIDs and witness times are
 * one real run's, not illustrations of one.
 *
 * To regenerate after a receipt release, follow
 * scripts/receipt-verify-demo/README.md: capture.py drives the new version,
 * reproduce.py re-proves every capture through the installed console script,
 * and generate.py rewrites this file.
 */

export const RECEIPT_VERSION = "0.6.0";

/** The corpus the transcripts are of, and the auditor's pins over it. */
export const CORPUS = {
  fixture: "TheAxiomFoundation/receipt @ v0.6.0 tests/corpus_fixture.py",
  genesis: "f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1",
  published: "763da642b55a1a74215aaef685cd95e2654f2e7d",
  publishedTree: "63aa505709b7e98aae60e3a57cf43a59e91075ef",
  specSha256: "9fc86da2d2caaf1b2f6df784a8eaef9cc5e8325e5224b0ba5c5a6bbb1b9b97c1",
  producerSpki: "7c5feee2d8f0cecbe27938422b1d95bbd25f27f644615d8c16e9e5254c058ae4",
} as const;

export type AttackId =
  | "pristine"
  | "rewrite"
  | "reencode"
  | "swapkey"
  | "rewitness"
  | "dropgate";

/** How much the auditor pinned on the command line before running it. */
export type Pin = "none" | "baseRef" | "pinned";

export type Transcript = {
  /** The invocation, as the capture recorded it. */
  command: string;
  exitCode: number;
  /** receipt writes a passing verdict to stdout and a refusal to stderr. */
  stream: "stdout" | "stderr";
  /** The stream's exact text. */
  text: string;
};

export const TRANSCRIPTS: Record<AttackId, Record<Pin, Transcript>> = {
  pristine: {
    none: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/pristine/corpus --commit HEAD",
      exitCode: 0,
      stream: "stdout",
      text: `receipt 0.6.0 — receipt test corpus
  root  /private/tmp/receipt-demo/pristine/corpus
  commit 763da642b55a1a74215aaef685cd95e2654f2e7d (tree 63aa505709b7e98aae60e3a57cf43a59e91075ef)
  names portable
  objects not requested
  spec  /private/tmp/receipt-demo/auditor/spec.py
        sha256 9fc86da2d2caaf1b2f6df784a8eaef9cc5e8325e5224b0ba5c5a6bbb1b9b97c1

ESTABLISHED OFFLINE, FROM THIS CLONE ALONE
  [ok  ] custody
         2 release(s), HEAD 0001-e8621fb527b805e3.json; head e8621fb527b805e3291225c0dc4b62669dbcf4523706a6ff989aed74c2386bb0; producer SPKI 7c5feee2d8f0cecb…; anchor set 740589de172785ff2685cd652105473a01d8523ddbb278b7660428e88acd19a8; witnesses alpha 2026-09-05T17:06:17Z · beta 2026-09-05T17:06:17Z
  [ok  ] binding
         3 content file(s) and 1 attested file(s) match the witnessed journal exactly, closed-world
  [ok  ] declaration
         3 gate declaration(s) well formed and complete against the loaded spec (1 public, 1 restricted, 1 ci-attested); none re-run here

DECLARED IN THE WITNESSED JOURNAL — NOT RE-RUN BY THIS COMMAND
  public: you can re-run these yourself from public inputs
    - rulespec/compile
  restricted: reproducible only with restricted pinned inputs this command cannot obtain
    - oracle/licensed-parity
  ci-attested: not reproducible; only the CI run's identity vouches
    - ci/repository-checks

VERDICT: PASS — custody and corpus binding
  This proves the published rule files are exactly the bytes the loaded
  spec's producer key signed,
  and the 2 RFC 3161 authorities configured by that spec (alpha, beta)
  witnessed that each recorded prefix existed no later than those times.
  Custody is under the anchor set 740589de172785ff2685cd652105473a01d8523ddbb278b7660428e88acd19a8 the verified tree carries.
  It does NOT prove the history was never rewritten — a producer holding
  the signing key can regenerate and re-witness a whole chain, and this
  first-contact check would still pass; supply --base-ref against a head
  you recorded earlier to bind against that. It does
  NOT prove that any declared gate passed, it does NOT prove the encodings
  are a correct reading of the law, it does NOT prove this clone holds the
  producer's newest release, and it does NOT prove this is the only history
  the producer maintains — a stale or equivocated but honestly witnessed
  clone may pass, and this verdict does NOT prove that files in any checkout
  equal the verified tree.
  It does NOT establish that the spec's code was trusted.
  It does NOT establish that the anchor set is one the auditor trusts.
  Check freshness and uniqueness by comparing head
  digests out of band.`,
    },
    baseRef: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/pristine/corpus --commit HEAD --base-ref f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1",
      exitCode: 2,
      stream: "stderr",
      text: `receipt verify: --base-ref requires --expect-commit
receipt verify: FAIL`,
    },
    pinned: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/pristine/corpus --commit HEAD --expect-commit 763da642b55a1a74215aaef685cd95e2654f2e7d --base-ref f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1",
      exitCode: 0,
      stream: "stdout",
      text: `receipt 0.6.0 — receipt test corpus
  root  /private/tmp/receipt-demo/pristine/corpus
  commit 763da642b55a1a74215aaef685cd95e2654f2e7d (tree 63aa505709b7e98aae60e3a57cf43a59e91075ef)
  base f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1 (tree fa390aad75ba411a6f94ac00f598eb7c44bc80f9)
  names portable
  objects not requested
  spec  /private/tmp/receipt-demo/auditor/spec.py
        sha256 9fc86da2d2caaf1b2f6df784a8eaef9cc5e8325e5224b0ba5c5a6bbb1b9b97c1

ESTABLISHED OFFLINE, FROM THIS CLONE ALONE
  [ok  ] history
         every release object present at f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1 (f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1) is byte- and mode-identical in tree 63aa505709b7
  [ok  ] custody
         2 release(s), HEAD 0001-e8621fb527b805e3.json; head e8621fb527b805e3291225c0dc4b62669dbcf4523706a6ff989aed74c2386bb0; producer SPKI 7c5feee2d8f0cecb…; anchor set 740589de172785ff2685cd652105473a01d8523ddbb278b7660428e88acd19a8; witnesses alpha 2026-09-05T17:06:17Z · beta 2026-09-05T17:06:17Z
  [ok  ] binding
         3 content file(s) and 1 attested file(s) match the witnessed journal exactly, closed-world
  [ok  ] declaration
         3 gate declaration(s) well formed and complete against the loaded spec (1 public, 1 restricted, 1 ci-attested); none re-run here

DECLARED IN THE WITNESSED JOURNAL — NOT RE-RUN BY THIS COMMAND
  public: you can re-run these yourself from public inputs
    - rulespec/compile
  restricted: reproducible only with restricted pinned inputs this command cannot obtain
    - oracle/licensed-parity
  ci-attested: not reproducible; only the CI run's identity vouches
    - ci/repository-checks

VERDICT: PASS — custody and corpus binding
  This proves the published rule files are exactly the bytes the loaded
  spec's producer key signed,
  and the 2 RFC 3161 authorities configured by that spec (alpha, beta)
  witnessed that each recorded prefix existed no later than those times,
  and every release object present at the supplied base reference is
  byte- and mode-identical in this tree.
  Custody is under the anchor set 740589de172785ff2685cd652105473a01d8523ddbb278b7660428e88acd19a8 the verified tree carries.
  It does
  NOT prove that any declared gate passed, it does NOT prove the encodings
  are a correct reading of the law, it does NOT prove this clone holds the
  producer's newest release, and it does NOT prove this is the only history
  the producer maintains — a stale or equivocated but honestly witnessed
  clone may pass, and this verdict does NOT prove that files in any checkout
  equal the verified tree.
  It does NOT establish that the spec's code was trusted.
  It does NOT establish that the anchor set is one the auditor trusts.
  Check freshness and uniqueness by comparing head
  digests out of band.`,
    },
  },
  rewrite: {
    none: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/hand-edit/corpus --commit HEAD",
      exitCode: 1,
      stream: "stderr",
      text: `receipt 0.6.0 — receipt test corpus
  root  /private/tmp/receipt-demo/hand-edit/corpus
  commit a737093489217f9d0fec001fbcdf113b8fa01c7e (tree 4809b3140b262cfdb8cd4c4feb38f19251426d26)
  names portable
  objects not requested
  spec  /private/tmp/receipt-demo/auditor/spec.py
        sha256 9fc86da2d2caaf1b2f6df784a8eaef9cc5e8325e5224b0ba5c5a6bbb1b9b97c1

PASSES
  [ok  ] custody
         2 release(s), HEAD 0001-e8621fb527b805e3.json; head e8621fb527b805e3291225c0dc4b62669dbcf4523706a6ff989aed74c2386bb0; producer SPKI 7c5feee2d8f0cecb…; anchor set 740589de172785ff2685cd652105473a01d8523ddbb278b7660428e88acd19a8; witnesses alpha 2026-09-05T17:06:17Z · beta 2026-09-05T17:06:17Z
  [FAIL] binding
         content file 'rules/tax/rate.yaml' does not match its witnessed digest: tree has c0f597cf00ba8050cdd6c8578e255c2bf364d1a00890b50d092bfd5df1f47348, journal binds e218ac6d2f126c76eb6e74203814e06e3fd528afc809576cede2e2b2546bdc49
  [FAIL] declaration
         not reached

FAILED: binding
  content file 'rules/tax/rate.yaml' does not match its witnessed digest: tree has c0f597cf00ba8050cdd6c8578e255c2bf364d1a00890b50d092bfd5df1f47348, journal binds e218ac6d2f126c76eb6e74203814e06e3fd528afc809576cede2e2b2546bdc49

VERDICT: FAIL — binding`,
    },
    baseRef: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/hand-edit/corpus --commit HEAD --base-ref f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1",
      exitCode: 2,
      stream: "stderr",
      text: `receipt verify: --base-ref requires --expect-commit
receipt verify: FAIL`,
    },
    pinned: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/hand-edit/corpus --commit HEAD --expect-commit a737093489217f9d0fec001fbcdf113b8fa01c7e --base-ref f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1",
      exitCode: 1,
      stream: "stderr",
      text: `receipt 0.6.0 — receipt test corpus
  root  /private/tmp/receipt-demo/hand-edit/corpus
  commit a737093489217f9d0fec001fbcdf113b8fa01c7e (tree 4809b3140b262cfdb8cd4c4feb38f19251426d26)
  base f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1 (tree fa390aad75ba411a6f94ac00f598eb7c44bc80f9)
  names portable
  objects not requested
  spec  /private/tmp/receipt-demo/auditor/spec.py
        sha256 9fc86da2d2caaf1b2f6df784a8eaef9cc5e8325e5224b0ba5c5a6bbb1b9b97c1

PASSES
  [ok  ] history
         every release object present at f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1 (f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1) is byte- and mode-identical in tree 4809b3140b26
  [ok  ] custody
         2 release(s), HEAD 0001-e8621fb527b805e3.json; head e8621fb527b805e3291225c0dc4b62669dbcf4523706a6ff989aed74c2386bb0; producer SPKI 7c5feee2d8f0cecb…; anchor set 740589de172785ff2685cd652105473a01d8523ddbb278b7660428e88acd19a8; witnesses alpha 2026-09-05T17:06:17Z · beta 2026-09-05T17:06:17Z
  [FAIL] binding
         content file 'rules/tax/rate.yaml' does not match its witnessed digest: tree has c0f597cf00ba8050cdd6c8578e255c2bf364d1a00890b50d092bfd5df1f47348, journal binds e218ac6d2f126c76eb6e74203814e06e3fd528afc809576cede2e2b2546bdc49
  [FAIL] declaration
         not reached

FAILED: binding
  content file 'rules/tax/rate.yaml' does not match its witnessed digest: tree has c0f597cf00ba8050cdd6c8578e255c2bf364d1a00890b50d092bfd5df1f47348, journal binds e218ac6d2f126c76eb6e74203814e06e3fd528afc809576cede2e2b2546bdc49

VERDICT: FAIL — binding`,
    },
  },
  reencode: {
    none: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/re-encode/corpus --commit HEAD",
      exitCode: 0,
      stream: "stdout",
      text: `receipt 0.6.0 — receipt test corpus
  root  /private/tmp/receipt-demo/re-encode/corpus
  commit 774ac5ff50920414771c7ddb4c7770a60191afbf (tree e2a7f6042a1bbd8acbd2efc75eceb4c4a49e2c73)
  names portable
  objects not requested
  spec  /private/tmp/receipt-demo/auditor/spec.py
        sha256 9fc86da2d2caaf1b2f6df784a8eaef9cc5e8325e5224b0ba5c5a6bbb1b9b97c1

ESTABLISHED OFFLINE, FROM THIS CLONE ALONE
  [ok  ] custody
         3 release(s), HEAD 0002-bae54c9f161430b3.json; head bae54c9f161430b32946bc88c9cbee4b109c05cb6b46159fa4b1030c879f4120; producer SPKI 7c5feee2d8f0cecb…; anchor set 740589de172785ff2685cd652105473a01d8523ddbb278b7660428e88acd19a8; witnesses alpha 2026-09-05T17:06:21Z · beta 2026-09-05T17:06:21Z
  [ok  ] binding
         3 content file(s) and 1 attested file(s) match the witnessed journal exactly, closed-world
  [ok  ] declaration
         3 gate declaration(s) well formed and complete against the loaded spec (1 public, 1 restricted, 1 ci-attested); none re-run here

DECLARED IN THE WITNESSED JOURNAL — NOT RE-RUN BY THIS COMMAND
  public: you can re-run these yourself from public inputs
    - rulespec/compile
  restricted: reproducible only with restricted pinned inputs this command cannot obtain
    - oracle/licensed-parity
  ci-attested: not reproducible; only the CI run's identity vouches
    - ci/repository-checks

VERDICT: PASS — custody and corpus binding
  This proves the published rule files are exactly the bytes the loaded
  spec's producer key signed,
  and the 2 RFC 3161 authorities configured by that spec (alpha, beta)
  witnessed that each recorded prefix existed no later than those times.
  Custody is under the anchor set 740589de172785ff2685cd652105473a01d8523ddbb278b7660428e88acd19a8 the verified tree carries.
  It does NOT prove the history was never rewritten — a producer holding
  the signing key can regenerate and re-witness a whole chain, and this
  first-contact check would still pass; supply --base-ref against a head
  you recorded earlier to bind against that. It does
  NOT prove that any declared gate passed, it does NOT prove the encodings
  are a correct reading of the law, it does NOT prove this clone holds the
  producer's newest release, and it does NOT prove this is the only history
  the producer maintains — a stale or equivocated but honestly witnessed
  clone may pass, and this verdict does NOT prove that files in any checkout
  equal the verified tree.
  It does NOT establish that the spec's code was trusted.
  It does NOT establish that the anchor set is one the auditor trusts.
  Check freshness and uniqueness by comparing head
  digests out of band.`,
    },
    baseRef: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/re-encode/corpus --commit HEAD --base-ref f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1",
      exitCode: 2,
      stream: "stderr",
      text: `receipt verify: --base-ref requires --expect-commit
receipt verify: FAIL`,
    },
    pinned: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/re-encode/corpus --commit HEAD --expect-commit 774ac5ff50920414771c7ddb4c7770a60191afbf --base-ref f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1",
      exitCode: 0,
      stream: "stdout",
      text: `receipt 0.6.0 — receipt test corpus
  root  /private/tmp/receipt-demo/re-encode/corpus
  commit 774ac5ff50920414771c7ddb4c7770a60191afbf (tree e2a7f6042a1bbd8acbd2efc75eceb4c4a49e2c73)
  base f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1 (tree fa390aad75ba411a6f94ac00f598eb7c44bc80f9)
  names portable
  objects not requested
  spec  /private/tmp/receipt-demo/auditor/spec.py
        sha256 9fc86da2d2caaf1b2f6df784a8eaef9cc5e8325e5224b0ba5c5a6bbb1b9b97c1

ESTABLISHED OFFLINE, FROM THIS CLONE ALONE
  [ok  ] history
         every release object present at f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1 (f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1) is byte- and mode-identical in tree e2a7f6042a1b
  [ok  ] custody
         3 release(s), HEAD 0002-bae54c9f161430b3.json; head bae54c9f161430b32946bc88c9cbee4b109c05cb6b46159fa4b1030c879f4120; producer SPKI 7c5feee2d8f0cecb…; anchor set 740589de172785ff2685cd652105473a01d8523ddbb278b7660428e88acd19a8; witnesses alpha 2026-09-05T17:06:21Z · beta 2026-09-05T17:06:21Z
  [ok  ] binding
         3 content file(s) and 1 attested file(s) match the witnessed journal exactly, closed-world
  [ok  ] declaration
         3 gate declaration(s) well formed and complete against the loaded spec (1 public, 1 restricted, 1 ci-attested); none re-run here

DECLARED IN THE WITNESSED JOURNAL — NOT RE-RUN BY THIS COMMAND
  public: you can re-run these yourself from public inputs
    - rulespec/compile
  restricted: reproducible only with restricted pinned inputs this command cannot obtain
    - oracle/licensed-parity
  ci-attested: not reproducible; only the CI run's identity vouches
    - ci/repository-checks

VERDICT: PASS — custody and corpus binding
  This proves the published rule files are exactly the bytes the loaded
  spec's producer key signed,
  and the 2 RFC 3161 authorities configured by that spec (alpha, beta)
  witnessed that each recorded prefix existed no later than those times,
  and every release object present at the supplied base reference is
  byte- and mode-identical in this tree.
  Custody is under the anchor set 740589de172785ff2685cd652105473a01d8523ddbb278b7660428e88acd19a8 the verified tree carries.
  It does
  NOT prove that any declared gate passed, it does NOT prove the encodings
  are a correct reading of the law, it does NOT prove this clone holds the
  producer's newest release, and it does NOT prove this is the only history
  the producer maintains — a stale or equivocated but honestly witnessed
  clone may pass, and this verdict does NOT prove that files in any checkout
  equal the verified tree.
  It does NOT establish that the spec's code was trusted.
  It does NOT establish that the anchor set is one the auditor trusts.
  Check freshness and uniqueness by comparing head
  digests out of band.`,
    },
  },
  swapkey: {
    none: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/swapped-key/corpus --commit HEAD",
      exitCode: 1,
      stream: "stderr",
      text: `receipt 0.6.0 — receipt test corpus
  root  /private/tmp/receipt-demo/swapped-key/corpus
  commit 7e15793081a294f7297668424292a87d172ef0a1 (tree fc87ae237ea4fd6bba4284f2c8419d8a6db45cf1)
  names portable
  objects not requested
  spec  /private/tmp/receipt-demo/auditor/spec.py
        sha256 9fc86da2d2caaf1b2f6df784a8eaef9cc5e8325e5224b0ba5c5a6bbb1b9b97c1

PASSES
  [FAIL] custody
         producer public-key SPKI is not code-pinned: 32d560e9732255c69b967cd4da17ce8c17b1c329c4f57fd6069a2378e03f53bf
  [FAIL] binding
         not reached

FAILED: custody
  producer public-key SPKI is not code-pinned: 32d560e9732255c69b967cd4da17ce8c17b1c329c4f57fd6069a2378e03f53bf

VERDICT: FAIL — custody`,
    },
    baseRef: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/swapped-key/corpus --commit HEAD --base-ref f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1",
      exitCode: 2,
      stream: "stderr",
      text: `receipt verify: --base-ref requires --expect-commit
receipt verify: FAIL`,
    },
    pinned: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/swapped-key/corpus --commit HEAD --expect-commit 7e15793081a294f7297668424292a87d172ef0a1 --base-ref f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1",
      exitCode: 1,
      stream: "stderr",
      text: `receipt 0.6.0 — receipt test corpus
  root  /private/tmp/receipt-demo/swapped-key/corpus
  commit 7e15793081a294f7297668424292a87d172ef0a1 (tree fc87ae237ea4fd6bba4284f2c8419d8a6db45cf1)
  base f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1 (tree fa390aad75ba411a6f94ac00f598eb7c44bc80f9)
  names portable
  objects not requested
  spec  /private/tmp/receipt-demo/auditor/spec.py
        sha256 9fc86da2d2caaf1b2f6df784a8eaef9cc5e8325e5224b0ba5c5a6bbb1b9b97c1

PASSES
  [FAIL] history
         release history is not immutable: existing release file bytes changed relative to f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1: releases/anchors/producer-ed25519.pub
  [FAIL] custody
         not reached

FAILED: history
  release history is not immutable: existing release file bytes changed relative to f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1: releases/anchors/producer-ed25519.pub

VERDICT: FAIL — history`,
    },
  },
  rewitness: {
    none: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/regenerated/corpus --commit HEAD",
      exitCode: 0,
      stream: "stdout",
      text: `receipt 0.6.0 — receipt test corpus
  root  /private/tmp/receipt-demo/regenerated/corpus
  commit dad2448f29cba555de1bca4c8bd9759bbfa13efb (tree 1fa82d34caeba4d17984b750dfe275a35ecb1ef6)
  names portable
  objects not requested
  spec  /private/tmp/receipt-demo/auditor/spec.py
        sha256 9fc86da2d2caaf1b2f6df784a8eaef9cc5e8325e5224b0ba5c5a6bbb1b9b97c1

ESTABLISHED OFFLINE, FROM THIS CLONE ALONE
  [ok  ] custody
         2 release(s), HEAD 0001-83afbd029eabb6b0.json; head 83afbd029eabb6b020880d0a5e55d802df74a969b90919093c31ff10bb0740b3; producer SPKI 7c5feee2d8f0cecb…; anchor set 740589de172785ff2685cd652105473a01d8523ddbb278b7660428e88acd19a8; witnesses alpha 2026-09-05T17:06:22Z · beta 2026-09-05T17:06:22Z
  [ok  ] binding
         3 content file(s) and 1 attested file(s) match the witnessed journal exactly, closed-world
  [ok  ] declaration
         3 gate declaration(s) well formed and complete against the loaded spec (1 public, 1 restricted, 1 ci-attested); none re-run here

DECLARED IN THE WITNESSED JOURNAL — NOT RE-RUN BY THIS COMMAND
  public: you can re-run these yourself from public inputs
    - rulespec/compile
  restricted: reproducible only with restricted pinned inputs this command cannot obtain
    - oracle/licensed-parity
  ci-attested: not reproducible; only the CI run's identity vouches
    - ci/repository-checks

VERDICT: PASS — custody and corpus binding
  This proves the published rule files are exactly the bytes the loaded
  spec's producer key signed,
  and the 2 RFC 3161 authorities configured by that spec (alpha, beta)
  witnessed that each recorded prefix existed no later than those times.
  Custody is under the anchor set 740589de172785ff2685cd652105473a01d8523ddbb278b7660428e88acd19a8 the verified tree carries.
  It does NOT prove the history was never rewritten — a producer holding
  the signing key can regenerate and re-witness a whole chain, and this
  first-contact check would still pass; supply --base-ref against a head
  you recorded earlier to bind against that. It does
  NOT prove that any declared gate passed, it does NOT prove the encodings
  are a correct reading of the law, it does NOT prove this clone holds the
  producer's newest release, and it does NOT prove this is the only history
  the producer maintains — a stale or equivocated but honestly witnessed
  clone may pass, and this verdict does NOT prove that files in any checkout
  equal the verified tree.
  It does NOT establish that the spec's code was trusted.
  It does NOT establish that the anchor set is one the auditor trusts.
  Check freshness and uniqueness by comparing head
  digests out of band.`,
    },
    baseRef: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/regenerated/corpus --commit HEAD --base-ref f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1",
      exitCode: 2,
      stream: "stderr",
      text: `receipt verify: --base-ref requires --expect-commit
receipt verify: FAIL`,
    },
    pinned: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/regenerated/corpus --commit HEAD --expect-commit dad2448f29cba555de1bca4c8bd9759bbfa13efb --base-ref f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1",
      exitCode: 1,
      stream: "stderr",
      text: `receipt 0.6.0 — receipt test corpus
  root  /private/tmp/receipt-demo/regenerated/corpus
  commit dad2448f29cba555de1bca4c8bd9759bbfa13efb (tree 1fa82d34caeba4d17984b750dfe275a35ecb1ef6)
  base f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1 (tree fa390aad75ba411a6f94ac00f598eb7c44bc80f9)
  names portable
  objects not requested
  spec  /private/tmp/receipt-demo/auditor/spec.py
        sha256 9fc86da2d2caaf1b2f6df784a8eaef9cc5e8325e5224b0ba5c5a6bbb1b9b97c1

PASSES
  [FAIL] history
         release history is not immutable: existing release file was deleted relative to f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1: releases/manifests/0000-eb8d7f5d21ccf5ce.alpha.tsr
  [FAIL] custody
         not reached

FAILED: history
  release history is not immutable: existing release file was deleted relative to f7c7baa2f6fc752b8a1af4b97f6ba7e339756ad1: releases/manifests/0000-eb8d7f5d21ccf5ce.alpha.tsr

VERDICT: FAIL — history`,
    },
  },
  dropgate: {
    none: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/undeclared-gate/corpus --commit HEAD",
      exitCode: 1,
      stream: "stderr",
      text: `receipt 0.6.0 — receipt test corpus
  root  /private/tmp/receipt-demo/undeclared-gate/corpus
  commit fe4492bc9750faed3bac050725814610d310670a (tree 8af9078a62b0aaf69bc42dc45aad2f59e2a30f79)
  names portable
  objects not requested
  spec  /private/tmp/receipt-demo/auditor/spec.py
        sha256 9fc86da2d2caaf1b2f6df784a8eaef9cc5e8325e5224b0ba5c5a6bbb1b9b97c1

PASSES
  [ok  ] custody
         2 release(s), HEAD 0001-a30feb3c93d4f804.json; head a30feb3c93d4f804823ebfa4da4c6eaf1ea1497478f5a0c9c8958c888c17cd77; producer SPKI 7c5feee2d8f0cecb…; anchor set 740589de172785ff2685cd652105473a01d8523ddbb278b7660428e88acd19a8; witnesses alpha 2026-09-05T17:06:23Z · beta 2026-09-05T17:06:23Z
  [ok  ] binding
         3 content file(s) and 1 attested file(s) match the witnessed journal exactly, closed-world
  [FAIL] declaration
         the witnessed journal does not declare a gate the pinned spec requires: 'rulespec/compile'

DECLARED IN THE WITNESSED JOURNAL — NOT RE-RUN BY THIS COMMAND
  restricted: reproducible only with restricted pinned inputs this command cannot obtain
    - oracle/licensed-parity
  ci-attested: not reproducible; only the CI run's identity vouches
    - ci/repository-checks

FAILED: declaration
  the witnessed journal does not declare a gate the pinned spec requires: 'rulespec/compile'

VERDICT: FAIL — declaration`,
    },
    baseRef: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/undeclared-gate/corpus --commit HEAD --base-ref e4dbd336fa11c084f3a60193cd7cbfadf2157e6b",
      exitCode: 2,
      stream: "stderr",
      text: `receipt verify: --base-ref requires --expect-commit
receipt verify: FAIL`,
    },
    pinned: {
      command: "receipt verify --spec /private/tmp/receipt-demo/auditor/spec.py --root /private/tmp/receipt-demo/undeclared-gate/corpus --commit HEAD --expect-commit fe4492bc9750faed3bac050725814610d310670a --base-ref e4dbd336fa11c084f3a60193cd7cbfadf2157e6b",
      exitCode: 1,
      stream: "stderr",
      text: `receipt 0.6.0 — receipt test corpus
  root  /private/tmp/receipt-demo/undeclared-gate/corpus
  commit fe4492bc9750faed3bac050725814610d310670a (tree 8af9078a62b0aaf69bc42dc45aad2f59e2a30f79)
  base e4dbd336fa11c084f3a60193cd7cbfadf2157e6b (tree fa188523e467a8341a8e4c0faebfe389f3536d93)
  names portable
  objects not requested
  spec  /private/tmp/receipt-demo/auditor/spec.py
        sha256 9fc86da2d2caaf1b2f6df784a8eaef9cc5e8325e5224b0ba5c5a6bbb1b9b97c1

PASSES
  [ok  ] history
         every release object present at e4dbd336fa11c084f3a60193cd7cbfadf2157e6b (e4dbd336fa11c084f3a60193cd7cbfadf2157e6b) is byte- and mode-identical in tree 8af9078a62b0
  [ok  ] custody
         2 release(s), HEAD 0001-a30feb3c93d4f804.json; head a30feb3c93d4f804823ebfa4da4c6eaf1ea1497478f5a0c9c8958c888c17cd77; producer SPKI 7c5feee2d8f0cecb…; anchor set 740589de172785ff2685cd652105473a01d8523ddbb278b7660428e88acd19a8; witnesses alpha 2026-09-05T17:06:23Z · beta 2026-09-05T17:06:23Z
  [ok  ] binding
         3 content file(s) and 1 attested file(s) match the witnessed journal exactly, closed-world
  [FAIL] declaration
         the witnessed journal does not declare a gate the pinned spec requires: 'rulespec/compile'

DECLARED IN THE WITNESSED JOURNAL — NOT RE-RUN BY THIS COMMAND
  restricted: reproducible only with restricted pinned inputs this command cannot obtain
    - oracle/licensed-parity
  ci-attested: not reproducible; only the CI run's identity vouches
    - ci/repository-checks

FAILED: declaration
  the witnessed journal does not declare a gate the pinned spec requires: 'rulespec/compile'

VERDICT: FAIL — declaration`,
    },
  },
};

/** What each attack's clone actually is, for the tree pane beside it. */
export const CLONES: Record<AttackId, { commit: string; tree: string; manifests: readonly string[] }> = {
  pristine: {
    commit: "763da642b55a1a74215aaef685cd95e2654f2e7d",
    tree: "63aa505709b7e98aae60e3a57cf43a59e91075ef",
    manifests: ["0000-eb8d7f5d21ccf5ce.json", "0001-e8621fb527b805e3.json"],
  },
  rewrite: {
    commit: "a737093489217f9d0fec001fbcdf113b8fa01c7e",
    tree: "4809b3140b262cfdb8cd4c4feb38f19251426d26",
    manifests: ["0000-eb8d7f5d21ccf5ce.json", "0001-e8621fb527b805e3.json"],
  },
  reencode: {
    commit: "774ac5ff50920414771c7ddb4c7770a60191afbf",
    tree: "e2a7f6042a1bbd8acbd2efc75eceb4c4a49e2c73",
    manifests: ["0000-eb8d7f5d21ccf5ce.json", "0001-e8621fb527b805e3.json", "0002-bae54c9f161430b3.json"],
  },
  swapkey: {
    commit: "7e15793081a294f7297668424292a87d172ef0a1",
    tree: "fc87ae237ea4fd6bba4284f2c8419d8a6db45cf1",
    manifests: ["0000-eb8d7f5d21ccf5ce.json", "0001-e8621fb527b805e3.json"],
  },
  rewitness: {
    commit: "dad2448f29cba555de1bca4c8bd9759bbfa13efb",
    tree: "1fa82d34caeba4d17984b750dfe275a35ecb1ef6",
    manifests: ["0000-8cb073855b4cea03.json", "0001-83afbd029eabb6b0.json"],
  },
  dropgate: {
    commit: "fe4492bc9750faed3bac050725814610d310670a",
    tree: "8af9078a62b0aaf69bc42dc45aad2f59e2a30f79",
    manifests: ["0000-1cbe0f4162c57e82.json", "0001-a30feb3c93d4f804.json"],
  },
};
